version: '3.8'
services:
  # テスト用DB
  postgres_test:
    image: postgres:16-alpine
    container_name: postgres-relumo-test
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: relumouser
      POSTGRES_PASSWORD: relumopass
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      POSTGRES_DB: relumo_test
    hostname: postgres
    restart: always
    user: root
