version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-relumo
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ${PWD}/docker/postgres/init.d
        target: /docker-entrypoint-initdb.d/
      - type: bind
        source: ${PWD}/docker/postgres/pgdata
        target: /docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: relumouser
      POSTGRES_PASSWORD: relumopass
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      POSTGRES_DB: relumo
    hostname: postgres
    restart: always
    user: root
  # テスト用DB
  postgres_test:
    image: postgres:16-alpine
    container_name: postgres-relumo-test
    ports:
      - 5433:5432
    volumes:
      - type: bind
        source: ${PWD}/docker/postgres/init.d
        target: /docker-entrypoint-initdb.d/
      - type: bind
        source: ${PWD}/docker/postgres/pgdata
        target: /docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: relumouser
      POSTGRES_PASSWORD: relumopass
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      POSTGRES_DB: relumo_test
    hostname: postgres
    restart: always
    user: root
