name: Node.js CI
on: [push]
jobs:
  test_run:
    runs-on: ubuntu-latest
    services:
      postgres_test:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: relumouser
          POSTGRES_PASSWORD: relumopass
          POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
          POSTGRES_DB: relumo_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
          cache: npm
      - run: npm ci
      - run: npm test
